name = "locationbackend"
main = "src/index.ts"
compatibility_date = "2023-04-29"

# GitHub Actions 환경 변수 설정
[env]
CLOUDFLARE_API_TOKEN = ""
CLOUDFLARE_ACCOUNT_ID = ""

[triggers]
crons = []

# 로컬 개발용 D1 데이터베이스 (실제 Cloudflare D1 사용)
[[ d1_databases ]]
binding = "DB"
database_name = "test-location-db"
database_id = "1b2b86d2-46d3-4850-95ae-791ac18d9c3d"

# 로컬 개발용 D1 데이터베이스 (CI 환경에서 사용)
[[ d1_databases ]]
binding = "DB"
database_name = "test-location-db"
database_id = "local"

# Custom Domain 설정
[env.production]
name = "jayneycoffee-api"
routes = [
  "jayneycoffee.api.location.rainclab.net/*"
]

# Production 환경에서 실제 D1 데이터베이스 사용
[[env.production.d1_databases]]
binding = "DB"
database_name = "jennycoffee_location"
database_id = "c6bfa5fe-bdda-44dd-8034-b7bbd447d19c"
